name: Ejemplo matriz

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        sistema_operativo: [windows-latest, ubuntu-latest, macos-latest]
    name: matriz uni-dimensional
    runs-on: ${{ matrix.sistema_operativo }}
    steps:
      - name: imprimir SO
        run: echo "Estamos en el sistema operativo ${{ matrix.sistema_operativo }}"
