name: Variables

on: 
  workflow_dispatch:

env:
  variable_global: VARIABLE GLOBAL

jobs:
  job-1:
    runs-on: ubuntu-latest
    env:
      variable_job: VARIABLE JOB
    steps:
      - name: step 1 dwl job 1
        run:  |
          echo el valor de la variable global es $variable_global
          echo 'el valor de la variable global es: ${{env.variable_global}}'
          echo 'el valor de la variable global es: ${{env.variable_job}}'
        env:
          variable-step: VARIABLE STEP

      - name: step 2 del job 1
        run: |
          echo 'seguimos con acceso a la variable del WF: ${{ env.variable_global}}'
          echo 'seguimos con acceso a la variable del job: ${{ env.variable_job }}'
  
  job-2:
    runs-on: ubuntu-latest
    steps:
    - name: step 1 del job 2
      run:  |
        echo 'seguimos con acceso a la variable del WF: ${{ env.variable_global}}'

        
