name: comandos workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Mensajes de warning y error
        run: | 
          echo: "Mensaje normal"
          echo "::warning::Mensaje de advertencia"
          echo "::error::Mensaje de ERROR"
